source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLStreamReport_Example', :exclusive => true do
  pod 'PLStreamReport', :path => '../'
end

target 'PLStreamReport_Tests', :exclusive => true do
  pod 'PLStreamReport', :path => '../'

  
end
